jobs:
  security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
    with:
      java-cache: maven
      java-version: 11
name: Jenkins Security Scan
on:
  repository_dispatch:
    types: trigger-ga___jenkins-security-scan.yml
permissions:
  actions: read
  contents: read
  security-events: write
