jobs:
  update_release_draft:
    if: github.repository_owner == 'jenkinsci'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v6
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yml
