jobs:
  sync-project-branch:
    if: github.repository_owner == 'jenkinsci'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: gsoc-2023-project
    - continue-on-error: true
      run: 'git fetch --unshallow origin || git fetch origin

        git config user.email "sync-project-branch@jenkins.io"

        git config user.name "Sync project branch action"

        git merge --no-edit origin/master

        '
    - continue-on-error: true
      uses: peter-evans/create-pull-request@v6
      with:
        branch: sync-project-branch
        delete-branch: true
        title: Merge remote-tracking branch `origin/master` into `gsoc-2023-project`
name: Sync project branch
on:
  repository_dispatch:
    types: trigger-ga___sync-project-branch.yml
